services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: weather
    ports:
      - 5434:5432
    volumes:
      - weather_db_data:/var/lib/postgresql/data

volumes:
  weather_db_data: