services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # image: weather_app
    # container_name: weather_app
    ports:
      - ${COMPOSE_BACKEND_PORT}:3000
    environment:
      PORT: 3000
      APP_URL: ${APP_URL}
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?schema=public
      WEATHER_API_KEY: ${WEATHER_API_KEY}

      SMTP_FROM: ${SMTP_FROM}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    depends_on:
      - db
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5434:5432
    volumes:
      - weather_db_data:/var/lib/postgresql/data

volumes:
  weather_db_data: