name: Backend Tests

on:
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/backend-tests.yml"

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-type:
          - name: "Functional Tests"
            command: "test"
          - name: "Architecture Validation"
            command: "arch:validate"

    name: ${{ matrix.test-type.name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "./backend/package-lock.json"

      - name: Install dependencies
        run: npm ci
        working-directory: ./backend

      - name: Run ${{ matrix.test-type.name }}
        run: npm run ${{ matrix.test-type.command }}
        working-directory: ./backend
